apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-risk-model
  labels:
    app: financial-risk-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-risk-model
  template:
    metadata:
      labels:
        app: financial-risk-model
    spec:
      containers:
      - name: financial-risk-model
        image: your-registry.com/financial-risk-model:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: financial-risk-model-secrets
              key: database-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: financial-risk-model-secrets
              key: secret-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10